# Generated by Django 2.1 on 2018-08-26 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrpage',
            name='ocr_document',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ocr.OcrDocument'),
            preserve_default=False,
        ),
    ]
